# Core Properties
nifi.flow.configuration.file=/opt/nifi/nifi-current/conf/flow.xml.gz
nifi.flow.configuration.archive.enabled=true
nifi.flow.configuration.archive.dir=/opt/nifi/nifi-current/conf/archive/
nifi.flowfile.repository.directory=/opt/nifi/nifi-current/flowfile_repository
nifi.database.directory=/opt/nifi/nifi-current/database_repository
nifi.content.repository.directory.default=/opt/nifi/nifi-current/content_repository
nifi.provenance.repository.directory.default=/opt/nifi/nifi-current/provenance_repository

# Web Properties
nifi.web.http.host=0.0.0.0
nifi.web.http.port=8080

# NAR Properties - Essential for NiFi to start
nifi.nar.library.directory=/opt/nifi/nifi-current/lib
nifi.nar.working.directory=/opt/nifi/nifi-current/work/nar

# Cluster Properties
nifi.cluster.is.node=false
nifi.cluster.node.protocol.port=8082
nifi.python.command=python

# State Management
nifi.state.management.configuration.file=/opt/nifi/nifi-current/conf/state-management.xml
nifi.state.management.provider.local=local-provider
nifi.state.management.provider.cluster=zk-provider
nifi.state.management.embedded.zookeeper.start=false
nifi.state.management.embedded.zookeeper.properties=
nifi.state.management.provider.local.class=org.apache.nifi.state.local.LocalStateProvider
nifi.state.management.provider.local.directory=/opt/nifi/nifi-current/state/local
